version: '1.0'
services:
  rabbitmq:
    image: rabbitmq:3.9.10-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"

#docker exec <RabbitMQ ContainerID> rabbitmq-plugins enable rabbitmq_mqtt